### ISSUE TITLE
Name for this game?

### ISSUE THREAD

**Issue by andr7430** [SyndicateFighter/SyndicateFighter#1]
name ideas?
1. ArcMonster
2. ArcFighter
3. Arcesri 
   [Aar-seh-si-ri] https://www.youtube.com/watch?v=NnKUOrHb9Ug
   [Aar-che-si-ri] https://www.youtube.com/watch?v=caU4UQ-BC3w 
4. GeoFighter
5. GeoMosnter
6. BizMonster
7. BizFighter

.
.
.

:shipit: 

i'm too invested

**Comment by andr7430** [comment]
I like 2 btw
Also, I actually have an android scaffold project ready for this, I am ready to push, but I'm holding off til we get a more concrete idea on the direction of this game

**Comment by nohe427** [comment]
I would say 2 or 7.

ArcFighter would be great if we were only going to market this internally.  I would say BizFighter is better since we could use this to potentially market externally.

**Comment by andr7430** [comment]
I agree, but is there another short word for business? biz sound like a cheezy early 2000s name.

**Comment by mohi7253** [comment]
I like ArcFighter or GeoFighter..

**Comment by david-chambers** [comment]
My vote is ArcFighter :facepunch:

**Comment by andr7430** [comment]
So the game be called ArcFighter or Syndicate Fighter?

This team is currently called "Syndicate Fighter" even though it looks like it is called "NotTheTeamYouAreLookingFor"

**Comment by andr7430** [comment]
we are having an identity crisis

**Comment by nohe427** [comment]
I think we shoud stay away from the word Arc as that can open up the market

**Comment by nohe427** [comment]
I think since we agreed on a name for this game, we can go ahead and close this issue?
