### ISSUE TITLE
Auto Sign in to Google Play Games

### ISSUE THREAD

**Issue by andr7430** [SyndicateFighter/SyndicateFighter#7]
I got a new project set up, and it now auto signs in to Google Play Games!
I will share with everyone the information in a private email as it includes keys and stuff. 

I can either push to this repro, or create a new one. Because it is no longer called arcmonsters...

It is now called:
com.arcfighter.SyndicateProjectGroup.SyndicateFighters
or simply 
SyndicateFighters

(because we don't want to involve "arc")

**Comment by andr7430** [comment]
Also, since the app needed to be signed for this, this means that it has passwords and stuff, how do we keep these secret on github?

**Comment by nohe427** [comment]
Create a pem file and distribute it via email. Just tell us where to use it
in the Readme

**Comment by nohe427** [comment]
Plus, do we still need a sign in for firebase?

**Comment by andr7430** [comment]
Yea, but there are password stored in the gradle files, and I expect these gradle files to be updated every so often, so I can't just not include them. Im looking into how others are doing it:
https://www.thoughtworks.com/insights/blog/signing-open-source-android-apps-without-disclosing-passwords

**Comment by andr7430** [comment]
I have yet to look into firebase integration. I will look into it tonight.

**Comment by nohe427** [comment]
I think it would be a separate portion and not automatic like google games from what I read.  I got email and password integration set up and if you're interested in doing google play we can do that one as well

**Comment by nohe427** [comment]
https://www.firebase.com/docs/web/guide/login/google.html might be of us

**Comment by andr7430** [comment]
im a genisu, i figured it out. it auto signs into google and firebase now

though there is a bug with it. I will update code soon

im done today, gn 
drop :microphone:

**Comment by andr7430** [comment]
200af2c297e2b5fa32e9ab35ea91c0b9c92f1edd

This is now closed.
